### PR TITLE
upgrade to Laravel 6.0

### LINKED ISSUE #39: Laravel 6.0
Will this package support Laravel 6.0?

### PR DESCRIPTION
**Pull request by neolikotsi**
close #39

### CODE REVIEW

**Comment by lloricode** [comment]
too much update, can you the specific changes,

**Comment by lloricode** [comment]
> "php": ">=7.0|^7.1.3",
"laravel/framework": "^5.5|^6.0"

@neolikotsi dont leave older version of laravel, it also compatible with it

**Comment by lloricode** [comment]
looks good, thanks @neolikotsi

**Comment by letrunghieu** [comment]
Thank you for your effort. I've updated this package with the release [4.0.0](https://github.com/letrunghieu/active/releases/tag/4.0.0)

**Pull request closed without merging**
