### PR TITLE
Add new method: query($key, $value, $class)

### PR DESCRIPTION
**Pull request by ilumos**
For checking URLs such as:

`http://my.app?tab=profile`

`Active::query('tab', 'profile')`

I have not written an accompanying test as I am very new to testing - sorry.

### CODE REVIEW

**Comment by letrunghieu** [comment]
I'll write unit test for this feature soon :smile:

**Comment by ilumos** [comment]
Awesome, thank you.

**Comment by letrunghieu** [comment]
The new method has been released in version `1.3.1` (for Laravel 4) and `2.1.1` (for Laravel 5)

**Comment by ilumos** [comment]
Thanks!

**Pull request merged**
